### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by marlonwilliams** [OpenSourceUniversity/bdn#1]
Trying to see a demo of this, but can't execute this step in the instructions because of missing contract files. Where can we find these?

`After successful compilation copy from OSUni platform directory - ./build/contracts/* to ./bdn/contracts/*
`

**Comment by MomchilJambazov** [comment]
Hello @marlonwilliams,

You need to compile the smart contracts from https://github.com/OpenSourceUniversity/platform

Best regards,
Momchil

**Comment by marlonwilliams** [comment]
https://github.com/OpenSourceUniversity/platform/tree/master/contracts is also empty. Can you show me where? Thx
